from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    AccountDeleteView,
    AccountProfileView,
    ChangePasswordView,
    EditProfileView,
    PublisherProfileView,
    RateLimitedLoginView,
    RateLimitedPasswordResetView,
)

urlpatterns = [
    path(
        "login/",
        RateLimitedLoginView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path(
        "password-reset/",
        RateLimitedPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="accounts/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="accounts/password_reset_confirm.html",
            success_url="/accounts/password-reset/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="accounts/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
    path(
        "change-password/",
        ChangePasswordView.as_view(),
        name="change_password",
    ),
    path(
        "delete/",
        AccountDeleteView.as_view(),
        name="account_delete",
    ),
    path(
        "profile/",
        AccountProfileView.as_view(),
        name="account_profile",
    ),
    path(
        "profile/edit/",
        EditProfileView.as_view(),
        name="edit_profile",
    ),
    path(
        "publishers/<str:username>/",
        PublisherProfileView.as_view(),
        name="publisher_profile",
    ),
]
