# Generated by Django 6.0.3 on 2026-03-15 00:19

import django.db.models.deletion
import events.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='events/images/', validators=[events.validators.validate_image_file])),
                ('image_thumbnail', models.ImageField(blank=True, editable=False, upload_to='events/thumbnails/')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('performance', 'Performance'), ('workshop', 'Workshop'), ('work_in_progress', 'Work in Progress'), ('open_practice', 'Open Practice'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=20)),
                ('is_free', models.BooleanField(default=False)),
                ('price_note', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, validators=[events.validators.validate_url_scheme])),
                ('external_source', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
    ]
