# Generated by Django 6.0.3 on 2026-03-29 20:38

import django.db.models.deletion
import events.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(choices=[('ical', 'iCal'), ('rss', 'RSS')], max_length=10)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('feed_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=4000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(choices=[('performance', 'Performance'), ('worksharing', 'Worksharing'), ('workshop', 'Workshop'), ('openpractice', 'Open Practice'), ('talk', 'Talk'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=20)),
                ('is_free', models.BooleanField(default=False)),
                ('is_wheelchair_accessible', models.BooleanField(default=False)),
                ('price_note', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, validators=[events.validators.validate_url_scheme])),
                ('external_source', models.CharField(blank=True, max_length=100)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_datetime'],
                'constraints': [models.UniqueConstraint(fields=('title', 'start_datetime'), name='unique_event_title_start_datetime')],
            },
        ),
    ]
