# Generated by Django 6.0.3 on 2026-03-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_draft",
            field=models.BooleanField(default=False),
        ),
    ]
