# Generated by Django 6.0.3 on 2026-03-16 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_event_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="rejection_note",
        ),
        migrations.RemoveField(
            model_name="event",
            name="status",
        ),
    ]
