# Generated by Django 6.0.6 on 2026-07-11 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_latitude_event_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_draft", "start_datetime"],
                name="events_even_is_draf_ab9f31_idx",
            ),
        ),
    ]
