# Generated by Django 6.0.4 on 2026-04-25 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_latitude_event_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventSeries",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=250, unique=True)),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True, max_length=4000)),
                ("external_source", models.CharField(blank=True, max_length=100)),
                ("external_key", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="event_series",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Event series",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.eventseries",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventseries",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_key", ""), _negated=True),
                fields=("external_source", "external_key"),
                name="unique_event_series_external_key",
            ),
        ),
    ]
