# Generated by Django 6.0.3 on 2026-03-28 18:12

from django.conf import settings
from django.db import migrations, models


def deduplicate_events(apps, schema_editor):
    """Remove duplicate events, keeping the most recently created one per (title, start_datetime)."""
    Event = apps.get_model("events", "Event")
    seen = set()
    for event in Event.objects.order_by("title", "start_datetime", "-created_at"):
        key = (event.title, event.start_datetime)
        if key in seen:
            event.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_is_draft_to_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_events, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('title', 'start_datetime'), name='unique_event_title_start_datetime'),
        ),
    ]
