# Generated by Django 6.0.4 on 2026-05-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_latitude_event_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="members_only_info",
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
