# Generated by Django 6.0.3 on 2026-03-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_remove_event_rejection_note_remove_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_wheelchair_accessible",
            field=models.BooleanField(default=False),
        ),
    ]
