# Generated by Django 6.1 on 2026-08-20 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_event_events_even_is_draf_ab9f31_idx"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_datetime", "id"]},
        ),
    ]
