# Generated by Django 6.1.1 on 2026-09-24 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_alter_event_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="unique_event_title_start_datetime",
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("title", "start_datetime", "venue_name"),
                name="unique_event_title_start_datetime_venue",
            ),
        ),
    ]
