# Generated by Django 6.0.3 on 2026-03-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_add_is_wheelchair_accessible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="image_thumbnail",
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
    ]
