# Generated by Django 6.0.3 on 2026-03-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_simplify_image_field_remove_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="category",
            field=models.CharField(
                choices=[
                    ("performance", "Performance"),
                    ("worksharing", "Worksharing"),
                    ("workshop", "Workshop"),
                    ("openpractice", "Open Practice"),
                    ("talk", "Talk"),
                    ("social", "Social"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
