# Generated by Django 6.1.1 on 2026-09-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_event_unique_title_start_venue"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description_da",
            field=models.TextField(
                blank=True, help_text="Danish part of a mixed-language description."
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="English version: machine translation of a Danish description, or the English part of a mixed-language one.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="description_en_is_machine",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="description_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("da", "Danish"),
                    ("en", "English"),
                    ("mixed", "Danish and English"),
                ],
                help_text="Language of the original description; blank = not processed.",
                max_length=5,
            ),
        ),
    ]
