# Generated by Django 6.1.1 on 2026-09-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_event_description_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image_source_url",
            field=models.URLField(blank=True, editable=False, max_length=2000),
        ),
    ]
