# Generated by Django 6.0.3 on 2026-03-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_update_event_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feed_type",
                    models.CharField(
                        choices=[("ical", "iCal"), ("rss", "RSS")], max_length=10
                    ),
                ),
                ("date", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("feed_type", "date")},
            },
        ),
    ]
