# Generated by Django 6.1.1 on 2026-09-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_event_image_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="thumbnail",
            field=models.ImageField(
                blank=True, editable=False, null=True, upload_to="events/thumbs/"
            ),
        ),
    ]
