# Generated by Django 6.1.1 on 2026-09-29 17:46

import re
from collections import defaultdict

from django.db import migrations, models

# Frozen copy of events.series.scraped_series_key as of this migration.
_TRAILING_DATE_RE = re.compile(r"/\d{4}-\d{2}-\d{2}/?$")


def link_existing_scraped_series(apps, schema_editor):
    """Group the dates of each scraped show already in the database."""
    Event = apps.get_model("events", "Event")
    EventSeries = apps.get_model("events", "EventSeries")
    groups = defaultdict(list)
    rows = (
        Event.objects.filter(series__isnull=True)
        .exclude(external_source="")
        .exclude(source_url="")
        .values_list("pk", "external_source", "source_url", "start_datetime")
    )
    for pk, source, url, start in rows:
        groups[f"{source}:{_TRAILING_DATE_RE.sub('/', url)}"].append((pk, start))
    for key, dates in groups.items():
        if len(dates) < 2:
            continue
        series = EventSeries.objects.create(
            source_key=key, dtstart=min(start for _pk, start in dates)
        )
        Event.objects.filter(pk__in=[pk for pk, _start in dates]).update(series=series)


def unlink_scraped_series(apps, schema_editor):
    EventSeries = apps.get_model("events", "EventSeries")
    EventSeries.objects.filter(rrule="").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_event_series"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventseries",
            name="source_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="eventseries",
            name="rrule",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name="eventseries",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_key", ""), _negated=True),
                fields=("source_key",),
                name="unique_event_series_source_key",
            ),
        ),
        migrations.RunPython(link_existing_scraped_series, unlink_scraped_series),
    ]
