# Generated by Django 6.1.1 on 2026-09-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailySalt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("salt", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="DailyCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("page", "Page view"),
                            ("visitors", "Unique visitors"),
                            ("referrer", "Referrer"),
                            ("search", "Search"),
                            ("filter", "Filter"),
                            ("calendar", "Calendar download"),
                        ],
                        max_length=20,
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=255)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["kind", "date"], name="analytics_d_kind_ea9e39_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "kind", "key"), name="unique_daily_count"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VisitorHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("digest", models.CharField(max_length=64)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "digest"), name="unique_visitor_hash"
                    )
                ],
            },
        ),
    ]
