# Generated by Django 6.0.3 on 2026-03-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_system_account",
            field=models.BooleanField(default=False),
        ),
    ]
