# Generated by Django 6.0.3 on 2026-04-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_configure_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimcode',
            name='claimed_by_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='claimcode',
            name='created_by_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
