# Generated by Django 6.0.3 on 2026-03-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_bio_website_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="intro_message",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
