# Generated by Django 6.0.3 on 2026-03-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_display_name_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
    ]
